name: Build Docs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

env:
  BUILD_DIR: .output
  PAGES_DIR: public

jobs:
  build-to-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Prepare /docs (disable Jekyll)
        run: |
          rm -rf "${PAGES_DIR}"
          mkdir -p "${PAGES_DIR}"
          cp -R "${BUILD_DIR}/." "${PAGES_DIR}/"
          touch "${PAGES_DIR}/.nojekyll"

      - name: Commit built site to /docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: build docs for GitHub Pages"
          file_pattern: "${{ env.PAGES_DIR }}/*"
